name: Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-web:latest

      - name: Run container from pushed image
        run: |
          docker stop my-web-container || true
          docker rm my-web-container || true
          docker run -d --name my-web-container -p 8888:80 ${{ secrets.DOCKER_USERNAME }}/my-web:latest
